-- =============================================
-- GenshinWalls Seed Data
-- 原神壁纸站种子数据
-- =============================================

-- 插入角色数据
INSERT INTO characters (id, name, name_cn, name_jp, element, weapon, rarity, region, release_version, avatar_url) VALUES
('raiden-shogun', 'Raiden Shogun', '雷电将军', '雷電将軍', 'electro', 'polearm', 5, 'inazuma', '2.1', 'https://example.com/avatars/raiden-shogun.webp'),
('hu-tao', 'Hu Tao', '胡桃', '胡桃', 'pyro', 'polearm', 5, 'liyue', '1.3', 'https://example.com/avatars/hu-tao.webp'),
('nahida', 'Nahida', '纳西妲', 'ナヒーダ', 'dendro', 'catalyst', 5, 'sumeru', '3.2', 'https://example.com/avatars/nahida.webp'),
('furina', 'Furina', '芙宁娜', 'フリーナ', 'hydro', 'sword', 5, 'fontaine', '4.2', 'https://example.com/avatars/furina.webp'),
('kazuha', 'Kaedehara Kazuha', '枫原万叶', '楓原万葉', 'anemo', 'sword', 5, 'inazuma', '1.6', 'https://example.com/avatars/kazuha.webp'),
('ayaka', 'Kamisato Ayaka', '神里绫华', '神里綾華', 'cryo', 'sword', 5, 'inazuma', '2.0', 'https://example.com/avatars/ayaka.webp'),
('zhongli', 'Zhongli', '钟离', '鍾離', 'geo', 'polearm', 5, 'liyue', '1.1', 'https://example.com/avatars/zhongli.webp'),
('xiao', 'Xiao', '魈', '魈', 'anemo', 'polearm', 5, 'liyue', '1.3', 'https://example.com/avatars/xiao.webp'),
('ganyu', 'Ganyu', '甘雨', '甘雨', 'cryo', 'bow', 5, 'liyue', '1.2', 'https://example.com/avatars/ganyu.webp'),
('yae-miko', 'Yae Miko', '八重神子', '八重神子', 'electro', 'catalyst', 5, 'inazuma', '2.5', 'https://example.com/avatars/yae-miko.webp'),
('yelan', 'Yelan', '夜兰', '夜蘭', 'hydro', 'bow', 5, 'liyue', '2.7', 'https://example.com/avatars/yelan.webp'),
('neuvillette', 'Neuvillette', '那维莱特', 'ヌヴィレット', 'hydro', 'catalyst', 5, 'fontaine', '4.1', 'https://example.com/avatars/neuvillette.webp'),
('alhaitham', 'Alhaitham', '艾尔海森', 'アルハイゼン', 'dendro', 'sword', 5, 'sumeru', '3.4', 'https://example.com/avatars/alhaitham.webp'),
('wanderer', 'Wanderer', '流浪者', '放浪者', 'anemo', 'catalyst', 5, 'sumeru', '3.3', 'https://example.com/avatars/wanderer.webp'),
('cyno', 'Cyno', '赛诺', 'セノ', 'electro', 'polearm', 5, 'sumeru', '3.1', 'https://example.com/avatars/cyno.webp'),
-- 4星角色
('fischl', 'Fischl', '菲谢尔', 'フィッシュル', 'electro', 'bow', 4, 'mondstadt', '1.0', 'https://example.com/avatars/fischl.webp'),
('xingqiu', 'Xingqiu', '行秋', '行秋', 'hydro', 'sword', 4, 'liyue', '1.0', 'https://example.com/avatars/xingqiu.webp'),
('xiangling', 'Xiangling', '香菱', '香菱', 'pyro', 'polearm', 4, 'liyue', '1.0', 'https://example.com/avatars/xiangling.webp'),
('bennett', 'Bennett', '班尼特', 'ベネット', 'pyro', 'sword', 4, 'mondstadt', '1.0', 'https://example.com/avatars/bennett.webp'),
('sucrose', 'Sucrose', '砂糖', 'スクロース', 'anemo', 'catalyst', 4, 'mondstadt', '1.0', 'https://example.com/avatars/sucrose.webp');

-- 插入壁纸数据
INSERT INTO wallpapers (title, slug, character_ids, element, region, source, thumbnail_url, preview_url, download_urls, tags, download_count, view_count, is_featured) VALUES
(
    'Raiden Shogun - Eternal Euthymia',
    'raiden-shogun-eternal-euthymia',
    ARRAY['raiden-shogun'],
    'electro',
    'inazuma',
    'official',
    'https://example.com/thumbnails/raiden-1.webp',
    'https://example.com/previews/raiden-1.webp',
    '{"mobile": "https://example.com/wallpapers/raiden-1-mobile.webp", "desktop": "https://example.com/wallpapers/raiden-1-desktop.webp", "desktop_4k": "https://example.com/wallpapers/raiden-1-4k.webp"}',
    ARRAY['raiden', 'electro', 'inazuma', 'archon', 'purple'],
    12580,
    45600,
    true
),
(
    'Hu Tao - Ghost of Wangsheng',
    'hu-tao-ghost-wangsheng',
    ARRAY['hu-tao'],
    'pyro',
    'liyue',
    'official',
    'https://example.com/thumbnails/hutao-1.webp',
    'https://example.com/previews/hutao-1.webp',
    '{"mobile": "https://example.com/wallpapers/hutao-1-mobile.webp", "desktop": "https://example.com/wallpapers/hutao-1-desktop.webp", "desktop_4k": "https://example.com/wallpapers/hutao-1-4k.webp"}',
    ARRAY['hu-tao', 'pyro', 'liyue', 'ghost', 'cute'],
    9870,
    32100,
    true
),
(
    'Nahida - Dendro Archon',
    'nahida-dendro-archon',
    ARRAY['nahida'],
    'dendro',
    'sumeru',
    'official',
    'https://example.com/thumbnails/nahida-1.webp',
    'https://example.com/previews/nahida-1.webp',
    '{"mobile": "https://example.com/wallpapers/nahida-1-mobile.webp", "desktop": "https://example.com/wallpapers/nahida-1-desktop.webp", "desktop_4k": "https://example.com/wallpapers/nahida-1-4k.webp"}',
    ARRAY['nahida', 'dendro', 'sumeru', 'archon', 'green', 'cute'],
    15230,
    52800,
    true
),
(
    'Furina - Hydro Archon Performance',
    'furina-hydro-archon-performance',
    ARRAY['furina'],
    'hydro',
    'fontaine',
    'official',
    'https://example.com/thumbnails/furina-1.webp',
    'https://example.com/previews/furina-1.webp',
    '{"mobile": "https://example.com/wallpapers/furina-1-mobile.webp", "desktop": "https://example.com/wallpapers/furina-1-desktop.webp", "desktop_4k": "https://example.com/wallpapers/furina-1-4k.webp"}',
    ARRAY['furina', 'hydro', 'fontaine', 'archon', 'blue', 'dramatic'],
    18500,
    61200,
    true
),
(
    'Kazuha - Autumn Maple',
    'kazuha-autumn-maple',
    ARRAY['kazuha'],
    'anemo',
    'inazuma',
    'fanart',
    'https://example.com/thumbnails/kazuha-1.webp',
    'https://example.com/previews/kazuha-1.webp',
    '{"mobile": "https://example.com/wallpapers/kazuha-1-mobile.webp", "desktop": "https://example.com/wallpapers/kazuha-1-desktop.webp"}',
    ARRAY['kazuha', 'anemo', 'inazuma', 'maple', 'autumn', 'samurai'],
    7650,
    28900,
    false
),
(
    'Zhongli - Rex Lapis Awakens',
    'zhongli-rex-lapis-awakens',
    ARRAY['zhongli'],
    'geo',
    'liyue',
    'official',
    'https://example.com/thumbnails/zhongli-1.webp',
    'https://example.com/previews/zhongli-1.webp',
    '{"mobile": "https://example.com/wallpapers/zhongli-1-mobile.webp", "desktop": "https://example.com/wallpapers/zhongli-1-desktop.webp", "desktop_4k": "https://example.com/wallpapers/zhongli-1-4k.webp"}',
    ARRAY['zhongli', 'geo', 'liyue', 'archon', 'dragon', 'gold'],
    14800,
    48700,
    true
),
(
    'Liyue Harbor Night View',
    'liyue-harbor-night-view',
    ARRAY[]::TEXT[],
    NULL,
    'liyue',
    'screenshot',
    'https://example.com/thumbnails/liyue-1.webp',
    'https://example.com/previews/liyue-1.webp',
    '{"mobile": "https://example.com/wallpapers/liyue-1-mobile.webp", "desktop": "https://example.com/wallpapers/liyue-1-desktop.webp", "desktop_4k": "https://example.com/wallpapers/liyue-1-4k.webp", "ultrawide": "https://example.com/wallpapers/liyue-1-ultrawide.webp"}',
    ARRAY['liyue', 'harbor', 'night', 'scenery', 'city', 'landscape'],
    6500,
    22400,
    false
),
(
    'Inazuma Thunder Storm',
    'inazuma-thunder-storm',
    ARRAY[]::TEXT[],
    'electro',
    'inazuma',
    'screenshot',
    'https://example.com/thumbnails/inazuma-1.webp',
    'https://example.com/previews/inazuma-1.webp',
    '{"mobile": "https://example.com/wallpapers/inazuma-1-mobile.webp", "desktop": "https://example.com/wallpapers/inazuma-1-desktop.webp", "desktop_4k": "https://example.com/wallpapers/inazuma-1-4k.webp"}',
    ARRAY['inazuma', 'storm', 'thunder', 'lightning', 'scenery', 'dramatic'],
    5800,
    19800,
    false
);
